### ISSUE TITLE
Browser-based requests need to use CORS too

### ISSUE THREAD

**Issue by annevk** [paulehoffman/draft-hoffman-dns-over-https#13]
It's unclear why browser-based DNS API requests can bypass the same-origin policy.

cc @sleevi

**Comment by mcmanus** [comment]
I'm unclear on why you think the text defines a bypass of sop. mght just be a -00 err

**Comment by annevk** [comment]
I guess it depends on how this integrates with the HTML and Fetch standards. If these requests are only done to the same origin as the navigation request is done, there's not really a problem. If these requests can go out more arbitrarily than that (or can happen as the result of a push), it becomes a little trickier.

**Comment by mcmanus** [comment]
this draft does explicitly call out building a https mechanism consistent with cors.. so if you think something is needed in this doc let me know.. do you think it should remain open?

**Comment by annevk** [comment]
I had the impression it only called that out for web applications, not for clients. (Should I reopen this at https://github.com/paulehoffman/draft-hoffman-dispatch-dns-over-https/issues/new? I missed that this repository moved...)

**Comment by mcmanus** [comment]
this draft is going to be at a protocol level, so it tries to apply to all implementations (including non browser clients - things like os resolving libraries).. so as far as its likely to go is to cite as motivation that by using DoH you are CORS  capable and allow use cases that want CORS to do CORS (which is what it tries to say) - which is an improvement for those use cases faced with the traditional dns protocol and no way to do cors.

as for what is subject to cors (and the scope of things like fetch) that already has other browser oriented forums to tussle that out in.. we should resolve separately.. I mostly agree with your above comments about integration with fetch etc..... there are probably different usage scenarios with different answers depending on context. (i.e something like push from content is radically different than an idle browser that is using DoH to bootstrap its own updates.. but its the intention that appropriate usage of this data, while it needs to be resolved, is not addressed here.

**Comment by annevk** [comment]
It's probably something you want to take into consideration into the design though as for instance the POST-style requests would require a CORS preflight if done across origins (due to unique Content-Type header value). That doesn't seem ideal. (Or we'd carve out another exception to the same-origin policy.)

Anyway, it does seem like something that needs to be resolved. If you don't want to track it here, maybe file an issue against https://github.com/whatwg/fetch/issues/new with some outline of how you'd expect this to be implemented in browser-like clients?

**Comment by mcmanus** [comment]
I agree about taking it into consideration and actually think preflight would be appropriate in cases where cors applied.. so I'm not sure we would need a preflight exception.

The first browser-like implementation is just in content script so it doesn't need a new definition.. cors clearly applies via existing fetch/xhr rules.

I'm going to close this as I don't think this effort needs more language, but feel free to reopen with a suggestion as necessary..

**Comment by annevk** [comment]
I'm not quite sure what a browser-like implementation in content script means. You mean there would be no changes to browsers? Also, how would content script be able to enforce H/2?

FYI: You cannot reopen GitHub issues on repositories that are not your own.

**Comment by mcmanus** [comment]
right.. so case #1 is a script that wants to look up an MX record from a particular DoH name or somesuch craziness. content supplies the doh endpoint info and the script uses xhr/fetch to do the doh. that should require no changes to browsers - let cors apply in all its glory.

case 2 (not ready for this yet) is where the browser supplies the doh nameserver endpoint, either via browser config or os config and this is just a transliteration of the old recursive resolver config.. we should talk it out - but plausibly this isn't a cors thing.

I think you're focusing on another case (3) which is about getting dns information from nav'd origins..  this document doesn't attempt to enable that behavior.. before that happens something else would need to describe the scope and applicability of that information.. it would be my hope that this draft could serve as the transport for that, but I ack that transport is just part of the picture.

interesting point about enforcing h2 in that scenario.. nextProtocol is available to content right?

**Comment by annevk** [comment]
Enforcing H/2 was about case 1. We might expose H/2 somewhere, but it's not exposed through any Fetch-related API. It might be in one of the resource timing APIs, but it's hard to couple those back to a specific request. (But I'm also not really concerned about this case. Content can do whatever anyway and indeed is restricted by the same-origin policy.)

Not sure I understand case 2.

And yeah, with case 3 I was thinking that when you navigate to x.com, x.com would supply the browser with some DNS API pushes that the browser can use to access CDNs and such without having to do old-fashioned DNS queries. And I was also thinking that if that's the plan, there's potential for trouble in the details.

**Comment by mcmanus** [comment]
I had forgotten github issues weren't self service reopen. sorry. let me know if you agree it can be closed now that its reopened.

case 2 would just be using a recursive resolver in the normal way except over http rather than dns-wire-protocol. (So the server is specified by OS/Config as now - content doesn't specify it in any way).

**Comment by annevk** [comment]
Okay, so yeah, the concern would solely apply with case 3 I think. If you could ping me whenever we start thinking that through I'd love to hear about it as I think it would be pretty neat to have.
