### ISSUE TITLE
provide a definition of the "same ID

### ISSUE THREAD

**Issue by mcmanus** [paulehoffman/draft-hoffman-dns-over-https#6]
from ben schwartz

The text is

   In order to maximize cache friendliness, DNS API Clients SHOULD use
   the same ID (the first two bytes of the header) for every DNS
   request.

That's enough to ensure that the same client making the same request hits the cache, but it's not enough to make sure that _different_ clients can hit a shared cache.  Even different tabs in the same browser won't share the browser cache unless they select matching IDs.

Personally, I would just skip these two bytes.  Instead of being "part of the DNS format", I think of the ID as being a generic miniature RPC protocol, which we are replacing with HTTP.  Failing that, I would say the ID MUST be zero.

**Comment by paulehoffman** [comment]
I am unclear on "but it's not enough to make sure that different clients can hit a shared cache". If the cache is a normal DNS cache, what you say is incorrect. Normal DNS caches don't store any of the header info other than the return code.

**Comment by mcmanus** [comment]
the shared cache in question is an http cache.. even the in-browser cache shared between applications (in this case applications are different pieces of javascript)

**Comment by paulehoffman** [comment]
Ah, got it. Would you have any objection to picking a "less obvious" number than 0? I sincerely worry about making an already-special-looking ID become more special.

**Comment by mcmanus** [comment]
fine by me..
