### ISSUE TITLE
security considerations (stephen f)

### ISSUE THREAD

**Issue by mcmanus** [paulehoffman/draft-hoffman-dns-over-https#7]
I think some small text addressing stephen's comments is apropos. Mostly about thinking about the scope of any result what you trust about the data and the entity that gave it to you.

 _I think this approach (and maybe others) has a missing
security consideration, that could be telling were this widely
deployed. IIUC, the same server here can, and is fairly likely
to, offer both DNS and the web over HTTPS. That has some nice
features, but also a downside - such a server is in a position
to choose which DNS entries it forces the client to resolve
and to also answer those queries. A client that then used
those DNS answers in another context (e.g. on another browser
tab, or cached OS-wide) could have bed consequences as it's
fairly easy to convince a browser to navigate to some bad
actor's web site and if that same bad actor could then poison
my DNS cache for any domain of it's choosing, then that is
a real worry. So I wonder if there needs to be some scoping
on the re-use of (non-DNSSEC) answers delivered via this
mechanism._

**Comment by paulehoffman** [comment]
Added wording about this in ba94c2a24f65ee474f7f2bb325cce2207207b08f.
